services:
  dist-test-run:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - CODEXDOCKERIMAGE=logosstorage/logos-storage-nim:sha-14c5270
      - BRANCH="feature/docker-image-testruns"
      - KUBECONFIG=/opt/kubeconfig
      - LOGPATH=/opt/logs
      - RUNNERLOCATION=ExternalToCluster

  continuous-test-run:
    image: thatbenbierens/dist-tests-deployandrun:initial
    environment:
      # - CODEXDOCKERIMAGE=imageoverride
      - DNR_REP=3
      - DNR_NAME=Tryout
      - DNR_FILTER=PeernBeer
      - DNR_DURATION=172800
